language: scala

scala:
  - 2.13.2

jdk:
  - openjdk8

before_install:
  - git fetch --tags

after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - name: test
      script: sbt compile scalafmtCheckAll test-coverage
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release